/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OnboardingTopicsRouteImport } from './routes/onboarding.topics'
import { Route as OnboardingPromptsRouteImport } from './routes/onboarding.prompts'
import { Route as OnboardingInsightsRouteImport } from './routes/onboarding.insights'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding.brand'
import { Route as OnboardingAnalyzingRouteImport } from './routes/onboarding.analyzing'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPromptsRouteImport } from './routes/app.prompts'
import { Route as AppMentionsRouteImport } from './routes/app.mentions'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppPromptsPromptIdRouteImport } from './routes/app.prompts.$promptId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingTopicsRoute = OnboardingTopicsRouteImport.update({
  id: '/onboarding/topics',
  path: '/onboarding/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPromptsRoute = OnboardingPromptsRouteImport.update({
  id: '/onboarding/prompts',
  path: '/onboarding/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInsightsRoute = OnboardingInsightsRouteImport.update({
  id: '/onboarding/insights',
  path: '/onboarding/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({
  id: '/onboarding/brand',
  path: '/onboarding/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAnalyzingRoute = OnboardingAnalyzingRouteImport.update({
  id: '/onboarding/analyzing',
  path: '/onboarding/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppMentionsRoute = AppMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsPromptIdRoute = AppPromptsPromptIdRouteImport.update({
  id: '/$promptId',
  path: '/$promptId',
  getParentRoute: () => AppPromptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/prompts': typeof AppPromptsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/insights': typeof OnboardingInsightsRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/topics': typeof OnboardingTopicsRoute
  '/app/': typeof AppIndexRoute
  '/app/prompts/$promptId': typeof AppPromptsPromptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/prompts': typeof AppPromptsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/insights': typeof OnboardingInsightsRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/topics': typeof OnboardingTopicsRoute
  '/app': typeof AppIndexRoute
  '/app/prompts/$promptId': typeof AppPromptsPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/prompts': typeof AppPromptsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/insights': typeof OnboardingInsightsRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/topics': typeof OnboardingTopicsRoute
  '/app/': typeof AppIndexRoute
  '/app/prompts/$promptId': typeof AppPromptsPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/alerts'
    | '/app/billing'
    | '/app/competitors'
    | '/app/mentions'
    | '/app/prompts'
    | '/app/settings'
    | '/app/team'
    | '/onboarding/analyzing'
    | '/onboarding/brand'
    | '/onboarding/company'
    | '/onboarding/insights'
    | '/onboarding/prompts'
    | '/onboarding/topics'
    | '/app/'
    | '/app/prompts/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/alerts'
    | '/app/billing'
    | '/app/competitors'
    | '/app/mentions'
    | '/app/prompts'
    | '/app/settings'
    | '/app/team'
    | '/onboarding/analyzing'
    | '/onboarding/brand'
    | '/onboarding/company'
    | '/onboarding/insights'
    | '/onboarding/prompts'
    | '/onboarding/topics'
    | '/app'
    | '/app/prompts/$promptId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/alerts'
    | '/app/billing'
    | '/app/competitors'
    | '/app/mentions'
    | '/app/prompts'
    | '/app/settings'
    | '/app/team'
    | '/onboarding/analyzing'
    | '/onboarding/brand'
    | '/onboarding/company'
    | '/onboarding/insights'
    | '/onboarding/prompts'
    | '/onboarding/topics'
    | '/app/'
    | '/app/prompts/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OnboardingAnalyzingRoute: typeof OnboardingAnalyzingRoute
  OnboardingBrandRoute: typeof OnboardingBrandRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OnboardingInsightsRoute: typeof OnboardingInsightsRoute
  OnboardingPromptsRoute: typeof OnboardingPromptsRoute
  OnboardingTopicsRoute: typeof OnboardingTopicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/topics': {
      id: '/onboarding/topics'
      path: '/onboarding/topics'
      fullPath: '/onboarding/topics'
      preLoaderRoute: typeof OnboardingTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/prompts': {
      id: '/onboarding/prompts'
      path: '/onboarding/prompts'
      fullPath: '/onboarding/prompts'
      preLoaderRoute: typeof OnboardingPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/insights': {
      id: '/onboarding/insights'
      path: '/onboarding/insights'
      fullPath: '/onboarding/insights'
      preLoaderRoute: typeof OnboardingInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/brand': {
      id: '/onboarding/brand'
      path: '/onboarding/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof OnboardingBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/analyzing': {
      id: '/onboarding/analyzing'
      path: '/onboarding/analyzing'
      fullPath: '/onboarding/analyzing'
      preLoaderRoute: typeof OnboardingAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts': {
      id: '/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentions': {
      id: '/app/mentions'
      path: '/mentions'
      fullPath: '/app/mentions'
      preLoaderRoute: typeof AppMentionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts/$promptId': {
      id: '/app/prompts/$promptId'
      path: '/$promptId'
      fullPath: '/app/prompts/$promptId'
      preLoaderRoute: typeof AppPromptsPromptIdRouteImport
      parentRoute: typeof AppPromptsRoute
    }
  }
}

interface AppPromptsRouteChildren {
  AppPromptsPromptIdRoute: typeof AppPromptsPromptIdRoute
}

const AppPromptsRouteChildren: AppPromptsRouteChildren = {
  AppPromptsPromptIdRoute: AppPromptsPromptIdRoute,
}

const AppPromptsRouteWithChildren = AppPromptsRoute._addFileChildren(
  AppPromptsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppMentionsRoute: typeof AppMentionsRoute
  AppPromptsRoute: typeof AppPromptsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppMentionsRoute: AppMentionsRoute,
  AppPromptsRoute: AppPromptsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OnboardingAnalyzingRoute: OnboardingAnalyzingRoute,
  OnboardingBrandRoute: OnboardingBrandRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  OnboardingInsightsRoute: OnboardingInsightsRoute,
  OnboardingPromptsRoute: OnboardingPromptsRoute,
  OnboardingTopicsRoute: OnboardingTopicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
