/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingTopicsRouteImport } from './routes/onboarding.topics'
import { Route as OnboardingPromptsRouteImport } from './routes/onboarding.prompts'
import { Route as OnboardingInsightsRouteImport } from './routes/onboarding.insights'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding.brand'
import { Route as OnboardingAnalyzingRouteImport } from './routes/onboarding.analyzing'
import { Route as IndexRouteImport } from './routes/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({ id: '/verify-email', path: '/verify-email', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({ id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport } as any)
const OnboardingTopicsRoute = OnboardingTopicsRouteImport.update({ id: '/onboarding/topics', path: '/onboarding/topics', getParentRoute: () => rootRouteImport } as any)
const OnboardingPromptsRoute = OnboardingPromptsRouteImport.update({ id: '/onboarding/prompts', path: '/onboarding/prompts', getParentRoute: () => rootRouteImport } as any)
const OnboardingInsightsRoute = OnboardingInsightsRouteImport.update({ id: '/onboarding/insights', path: '/onboarding/insights', getParentRoute: () => rootRouteImport } as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({ id: '/onboarding/company', path: '/onboarding/company', getParentRoute: () => rootRouteImport } as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({ id: '/onboarding/brand', path: '/onboarding/brand', getParentRoute: () => rootRouteImport } as any)
const OnboardingAnalyzingRoute = OnboardingAnalyzingRouteImport.update({ id: '/onboarding/analyzing', path: '/onboarding/analyzing', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/insights': typeof OnboardingInsightsRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/topics': typeof OnboardingTopicsRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/insights': typeof OnboardingInsightsRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/topics': typeof OnboardingTopicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forgot-password' | '/login' | '/reset-password' | '/signup' | '/verify-email' | '/onboarding/analyzing' | '/onboarding/brand' | '/onboarding/company' | '/onboarding/insights' | '/onboarding/prompts' | '/onboarding/topics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forgot-password' | '/login' | '/reset-password' | '/signup' | '/verify-email' | '/onboarding/analyzing' | '/onboarding/brand' | '/onboarding/company' | '/onboarding/insights' | '/onboarding/prompts' | '/onboarding/topics'
  id: '__root__' | '/' | '/forgot-password' | '/login' | '/reset-password' | '/signup' | '/verify-email' | '/onboarding/analyzing' | '/onboarding/brand' | '/onboarding/company' | '/onboarding/insights' | '/onboarding/prompts' | '/onboarding/topics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OnboardingAnalyzingRoute: typeof OnboardingAnalyzingRoute
  OnboardingBrandRoute: typeof OnboardingBrandRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OnboardingInsightsRoute: typeof OnboardingInsightsRoute
  OnboardingPromptsRoute: typeof OnboardingPromptsRoute
  OnboardingTopicsRoute: typeof OnboardingTopicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': { id: '/verify-email'; path: '/verify-email'; fullPath: '/verify-email'; preLoaderRoute: typeof VerifyEmailRouteImport; parentRoute: typeof rootRouteImport }
    '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof ResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/forgot-password': { id: '/forgot-password'; path: '/forgot-password'; fullPath: '/forgot-password'; preLoaderRoute: typeof ForgotPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding/topics': { id: '/onboarding/topics'; path: '/onboarding/topics'; fullPath: '/onboarding/topics'; preLoaderRoute: typeof OnboardingTopicsRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding/prompts': { id: '/onboarding/prompts'; path: '/onboarding/prompts'; fullPath: '/onboarding/prompts'; preLoaderRoute: typeof OnboardingPromptsRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding/insights': { id: '/onboarding/insights'; path: '/onboarding/insights'; fullPath: '/onboarding/insights'; preLoaderRoute: typeof OnboardingInsightsRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding/company': { id: '/onboarding/company'; path: '/onboarding/company'; fullPath: '/onboarding/company'; preLoaderRoute: typeof OnboardingCompanyRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding/brand': { id: '/onboarding/brand'; path: '/onboarding/brand'; fullPath: '/onboarding/brand'; preLoaderRoute: typeof OnboardingBrandRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding/analyzing': { id: '/onboarding/analyzing'; path: '/onboarding/analyzing'; fullPath: '/onboarding/analyzing'; preLoaderRoute: typeof OnboardingAnalyzingRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ForgotPasswordRoute,
  LoginRoute,
  ResetPasswordRoute,
  SignupRoute,
  VerifyEmailRoute,
  OnboardingAnalyzingRoute,
  OnboardingBrandRoute,
  OnboardingCompanyRoute,
  OnboardingInsightsRoute,
  OnboardingPromptsRoute,
  OnboardingTopicsRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
